### ISSUE TITLE
Divide by zero crash when applying cobweb to frame

### ISSUE THREAD

**Issue by saltyseadoggo** [alex5nader/Framity#24] opened 2021-01-12 20:50 UTC
[crash-2021-01-12_12.40.35-client.txt](https://github.com/alex5nader/Framed/files/5804726/crash-2021-01-12_12.40.35-client.txt)
This crash report comes from trying to apply a cobweb to a frame that already had a block texture (Sandwichable's salty sand) and the grass overlay applied to it. The world in which the crash occurred crashes the game whenever I attempt to load it now.

**Comment by saltyseadoggo** [comment] 2021-01-12 21:21
Upon further testing, this always occurs when attempting to apply the cobweb to a frame, regardless of what is on it.

**Comment by alex5nader** [comment] 2021-01-13 08:53
Hey, thanks for the report! I've figured out what the problem is and it'll be fixed in 1.0.2. Should be releasing soon.

**Closed as completed** 2021-01-13 09:53 UTC
Labels: bug
